# Generated by Django 5.2.4 on 2025-08-08 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CRM',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('phone_no', models.TextField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead_description', models.TextField(blank=True, null=True)),
                ('other_description', models.TextField(blank=True, null=True)),
                ('badge', models.TextField(blank=True, null=True)),
                ('lead_creation_date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'crm',
                'managed': True,
            },
        ),
    ]
