# Generated by Django 5.2.4 on 2025-08-13 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('phone_no', models.TextField(unique=True)),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('lead_description', models.TextField(blank=True, null=True)),
                ('other_description', models.TextField(blank=True, null=True)),
                ('lead_creation_date', models.DateField(blank=True, null=True)),
                ('praja_dashboard_user_link', models.TextField(blank=True, null=True)),
                ('lead_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('tenant_id', models.UUIDField(blank=True, null=True)),
                ('atleast_paid_once', models.BooleanField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('badge', models.CharField(blank=True, max_length=255, null=True)),
                ('display_pic_url', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'leads',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='CRM',
        ),
    ]
