# Generated by Django 5.2.4 on 2025-08-13 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_lead_assigned_to_lead_lead_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['tenant_id', '-created_at'], name='leads_tenant__e3efd8_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['assigned_to', 'lead_status', '-created_at'], name='leads_assigne_ef72fd_idx'),
        ),
    ]
