# Generated by Django 5.2.4 on 2025-08-14 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('crm', '0004_lead_updated_at_lead_leads_tenant__e3efd8_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='lead',
            name='leads_tenant__e3efd8_idx',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='tenant_id',
        ),
        migrations.AddField(
            model_name='lead',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='core.tenant'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['tenant', '-created_at'], name='leads_tenant__e3efd8_idx'),
        ),
    ]
