# Generated by Django 5.2.4 on 2025-08-19 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_remove_lead_leads_tenant__e3efd8_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='attempt_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lead',
            name='do_not_call',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='last_call_outcome',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='next_call_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
