# Generated by Django 5.2.4 on 2025-08-20 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('crm', '0006_lead_attempt_count_lead_do_not_call_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['lead_status', 'next_call_at'], name='leads_lead_st_8eb769_idx'),
        ),
    ]
