# Generated by Django 5.2.4 on 2025-08-27 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_alter_lead_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='resolved_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
