# Generated by Django 5.2.4

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('crm_records', '0004_ruleexecutionlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('job_type', models.CharField(choices=[('send_mixpanel_event', 'Send Mixpanel Event'), ('send_webhook', 'Send Webhook')], db_index=True, help_text='Type of job to execute', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('RETRYING', 'Retrying')], db_index=True, default='PENDING', help_text='Current status of the job', max_length=20)),
                ('priority', models.SmallIntegerField(db_index=True, default=0, help_text='Job priority (higher = more priority). 10=critical, 5=high, 0=normal, -5=low')),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Job-specific data required for execution')),
                ('attempts', models.PositiveSmallIntegerField(default=0, help_text='Number of processing attempts made')),
                ('max_attempts', models.PositiveSmallIntegerField(default=3, help_text='Maximum number of retry attempts before marking as failed')),
                ('last_error', models.TextField(blank=True, help_text='Last error message if job failed', null=True)),
                ('scheduled_at', models.DateTimeField(blank=True, db_index=True, help_text='When to schedule this job (for delayed execution)', null=True)),
                ('locked_by', models.CharField(blank=True, help_text='Worker identifier that has locked this job', max_length=64, null=True)),
                ('locked_at', models.DateTimeField(blank=True, help_text='When this job was locked by a worker', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the job was completed', null=True)),
                ('result', models.JSONField(blank=True, help_text='Job result data (if any)', null=True)),
                ('record', models.ForeignKey(blank=True, help_text='Optional reference to the record that triggered this job', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='background_jobs', to='crm_records.record')),
                ('tenant', models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='core.tenant')),
            ],
            options={
                'db_table': 'background_jobs',
                'ordering': ['-priority', 'created_at'],
                'indexes': [
                    models.Index(fields=['status', 'priority', '-created_at'], name='background_j_status_prior_idx'),
                    models.Index(fields=['status', 'scheduled_at'], name='background_j_status_sche_idx'),
                    models.Index(fields=['job_type', 'status'], name='background_j_job_typ_stat_idx'),
                    models.Index(fields=['tenant', 'status'], name='background_j_tenant_status_idx'),
                ],
            },
        ),
    ]


