# Generated by Django 5.2.4 on 2025-12-04 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('background_jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='backgroundjob',
            new_name='background__status_b03f2f_idx',
            old_name='background_j_status_prior_idx',
        ),
        migrations.RenameIndex(
            model_name='backgroundjob',
            new_name='background__status_d5252a_idx',
            old_name='background_j_status_sche_idx',
        ),
        migrations.RenameIndex(
            model_name='backgroundjob',
            new_name='background__job_typ_0be1ba_idx',
            old_name='background_j_job_typ_stat_idx',
        ),
        migrations.RenameIndex(
            model_name='backgroundjob',
            new_name='background__tenant__41282d_idx',
            old_name='background_j_tenant_status_idx',
        ),
    ]
