# Generated by Django 5.2.4 on 2025-12-04 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background_jobs', '0002_rename_background_j_status_prior_idx_background__status_b03f2f_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundjob',
            name='job_type',
            field=models.CharField(choices=[('send_mixpanel_event', 'Send Mixpanel Event'), ('send_webhook', 'Send Webhook'), ('execute_function', 'Execute Function')], db_index=True, help_text='Type of job to execute', max_length=50),
        ),
    ]
