# Generated by Django 5.2.4 on 2025-12-04 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('background_jobs', '0003_alter_backgroundjob_job_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backgroundjob',
            name='record',
        ),
    ]
