# Generated by Django 5.2.4 on 2025-12-11 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background_jobs', '0004_remove_backgroundjob_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundjob',
            name='job_type',
            field=models.CharField(choices=[('send_mixpanel_event', 'Send Mixpanel Event'), ('send_webhook', 'Send Webhook'), ('execute_function', 'Execute Function'), ('score_leads', 'Score Leads')], db_index=True, help_text='Type of job to execute', max_length=50),
        ),
    ]
