# Generated by Django 5.2.4 on 2026-02-10 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background_jobs', '0005_add_score_leads_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundjob',
            name='job_type',
            field=models.CharField(choices=[('send_mixpanel_event', 'Send Mixpanel Event'), ('send_webhook', 'Send Webhook'), ('execute_function', 'Execute Function'), ('score_leads', 'Score Leads'), ('send_to_praja', 'Send to Praja Server')], db_index=True, help_text='Type of job to execute', max_length=50),
        ),
    ]
