# Generated by Django 5.2.4 on 2026-04-29 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background_jobs', '0012_backgroundjob_soft_delete'),
        ('core', '0004_idle_in_transaction_session_timeout'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='backgroundjob',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='backgroundjob',
            name='is_deleted',
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='backgroundjob',
            name='job_type',
            field=models.CharField(choices=[('send_mixpanel_event', 'Send Mixpanel Event'), ('send_rm_assigned_event', 'Send RM Assigned Event'), ('send_webhook', 'Send Webhook'), ('execute_function', 'Execute Function'), ('score_leads', 'Score Leads'), ('score_leads_chunk', 'Score Leads Chunk'), ('send_to_praja', 'Send to Praja Server'), ('partner_lead_assign', 'Partner Lead Assign'), ('unassign_snoozed_leads', 'Unassign Snoozed Leads'), ('release_leads_after_12h', 'Release Leads After 12h'), ('close_stale_subscription_leads', 'Close Stale Subscription Leads'), ('snoozed_to_not_connected_midnight', 'Snoozed To Not Connected (midnight)')], db_index=True, help_text='Type of job to execute', max_length=50),
        ),
        migrations.AddIndex(
            model_name='backgroundjob',
            index=models.Index(fields=['tenant', '-created_at'], name='background__tenant__a1621e_idx'),
        ),
    ]
