# Generated by Django 5.2.4 on 2025-09-25 13:55

from django.db import migrations, models
from django.utils import timezone

class Migration(migrations.Migration):
    # This tells Django the squashed file replaces the older ones.
    replaces = [
        ('support_ticket', '0001_supportticket_state'),
        ('support_ticket', '0002_move_ct_perms'),
        ('support_ticket', '0003_supportticketdump'),
        ('support_ticket', '0004_alter_supportticket_options'),
    ]
    initial = True

    dependencies = [
        ('core', '__latest__'),
        ('accounts', '0003_supabaseauthuser'),  # Pinned so adding accounts.0004 doesn't break existing DBs
        ('contenttypes', '__latest__'),
        ('auth', '__latest__'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=timezone.now)),
                ('ticket_date', models.DateTimeField(blank=True, null=True)),

                ('user_id', models.CharField(max_length=255, blank=True, null=True)),
                ('name', models.CharField(max_length=255, blank=True, null=True)),
                ('phone', models.CharField(max_length=50, blank=True, null=True)),
                ('source', models.CharField(max_length=255, blank=True, null=True)),

                ('subscription_status', models.TextField(blank=True, null=True)),
                ('atleast_paid_once', models.BooleanField(blank=True, null=True)),

                ('reason', models.TextField(blank=True, null=True)),
                # If you need ArrayField here for fresh installs, you can add it;
                # but ArrayField in migrations requires contrib.postgres. To keep the
                # initial migration simple & portable, you may add it later via AlterField.
                # ('other_reasons', ArrayField(models.TextField(), blank=True, null=True)),

                ('badge', models.CharField(max_length=255, blank=True, null=True)),
                ('poster', models.CharField(max_length=255, blank=True, null=True)),

                ('layout_status', models.CharField(max_length=255, blank=True, null=True)),
                ('resolution_status', models.CharField(max_length=255, blank=True, null=True)),
                ('resolution_time', models.CharField(max_length=255, blank=True, null=True)),

                ('cse_name', models.CharField(max_length=255, blank=True, null=True)),
                ('cse_remarks', models.TextField(blank=True, null=True)),
                ('call_status', models.CharField(max_length=255, blank=True, null=True)),
                ('call_attempts', models.IntegerField(default=0, blank=True, null=True)),

                ('rm_name', models.TextField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('snooze_until', models.DateTimeField(blank=True, null=True)),
                ('praja_dashboard_user_link', models.TextField(blank=True, null=True)),
                ('display_pic_url', models.TextField(blank=True, null=True)),
                ('dumped_at', models.DateTimeField(blank=True, null=True)),

                # Foreign keys with explicit db_column names
                ('tenant', models.ForeignKey(
                    to='core.tenant',
                    db_column='tenant_id',
                    on_delete=models.DO_NOTHING,
                    null=True, blank=True,
                    related_name='support_tickets',
                )),
                ('assigned_to', models.ForeignKey(
                    to='accounts.supabaseauthuser',
                    db_column='assigned_to',
                    on_delete=models.CASCADE,
                    null=True, blank=True,
                    related_name='assigned_tickets',
                )),
            ],
            options={
                'db_table': 'support_ticket',
                'managed': True,
            },
        ),
    ]
