# Generated by Django 5.2.4 on 2025-09-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_ticket', '0002_move_ct_perms'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicketDump',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket_date', models.DateTimeField(blank=True, null=True)),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('subscription_status', models.TextField(blank=True, null=True)),
                ('atleast_paid_once', models.BooleanField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('badge', models.CharField(blank=True, max_length=255, null=True)),
                ('poster', models.CharField(blank=True, max_length=255, null=True)),
                ('tenant_id', models.UUIDField()),
                ('layout_status', models.CharField(blank=True, max_length=255, null=True)),
                ('praja_dashboard_user_link', models.TextField(blank=True, null=True)),
                ('display_pic_url', models.TextField(blank=True, null=True)),
                ('is_processed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'support_ticket_dump',
                'managed': False,
            },
        ),
    ]
