# Generated by Django 5.2.4 on 2025-09-25 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support_ticket', '0003_supportticketdump'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supportticket',
            options={'managed': True},
        ),
    ]
