# Generated by Django 5.2.4 on 2025-10-01 06:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_ticket', '0006_add_foreign_keys_if_missing'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='other_reasons',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='review_requested',
            field=models.BooleanField(blank=True, help_text='Whether CSE requested customer to post a review', null=True),
        ),
        migrations.CreateModel(
            name='SupportTicketDump',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket_date', models.DateTimeField(blank=True, null=True)),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('subscription_status', models.TextField(blank=True, null=True)),
                ('atleast_paid_once', models.BooleanField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('badge', models.CharField(blank=True, max_length=255, null=True)),
                ('poster', models.CharField(blank=True, max_length=255, null=True)),
                ('tenant_id', models.UUIDField()),
                ('layout_status', models.CharField(blank=True, max_length=255, null=True)),
                ('praja_dashboard_user_link', models.TextField(blank=True, null=True)),
                ('display_pic_url', models.TextField(blank=True, null=True)),
                ('is_processed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'support_ticket_dump',
                'managed': True,
                'indexes': [models.Index(fields=['tenant_id', '-created_at'], name='std_tn_cr_desc'), models.Index(fields=['is_processed', '-created_at'], name='std_proc_cr')],
            },
        ),
    ]
