# Generated by Django 5.2.4 on 2025-12-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_ticket', '0007_supportticket_other_reasons_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticketdump',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]

