# Generated by Django 5.2.4 on 2026-02-10 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support_ticket', '0009_add_pyro_support'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PyroSupport',
        ),
    ]
