# Generated by Django 5.2.4

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('title', models.CharField(help_text='Title of the WhatsApp template', max_length=255)),
                ('description', models.TextField(help_text='Description/content of the WhatsApp template')),
                ('tenant', models.ForeignKey(blank=True, db_column='tenant_id', db_index=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_whatsapptemplate_set', to='core.tenant')),
            ],
            options={
                'db_table': 'whatsapp_templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='whatsapptemplate',
            index=models.Index(fields=['tenant', '-created_at'], name='whatsapp_te_tenant__idx'),
        ),
        migrations.AddIndex(
            model_name='whatsapptemplate',
            index=models.Index(fields=['tenant', 'title'], name='whatsapp_te_tenant__title_idx'),
        ),
    ]
