# Generated by Django 5.2.4 on 2026-01-16 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='whatsapptemplate',
            new_name='whatsapp_te_tenant__f5c841_idx',
            old_name='whatsapp_te_tenant__idx',
        ),
        migrations.RenameIndex(
            model_name='whatsapptemplate',
            new_name='whatsapp_te_tenant__106655_idx',
            old_name='whatsapp_te_tenant__title_idx',
        ),
        migrations.AlterField(
            model_name='whatsapptemplate',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='core.tenant'),
        ),
    ]
