# Generated by Django 5.2.4 on 2026-04-29 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0003_whatsapptemplate_soft_delete'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='whatsapptemplate',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='whatsapptemplate',
            name='is_deleted',
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
    ]
