from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("accounts", "0003_supabaseauthuser"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ObjectHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("object_id", models.TextField()),
                ("object_repr", models.TextField()),
                ("action", models.CharField(max_length=32)),
                ("actor_label", models.CharField(blank=True, max_length=255, null=True)),
                ("version", models.PositiveIntegerField()),
                ("changes", models.JSONField(blank=True, default=dict)),
                ("before_state", models.JSONField(blank=True, null=True)),
                ("after_state", models.JSONField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "actor_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="object_history_entries",
                        to="accounts.supabaseauthuser",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="object_history_entries",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        db_column="tenant_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="object_history_objecthistory_set",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "object_history",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "-created_at"],
                        name="core_basemodel_tenant_created_at_idx",
                    ),
                    models.Index(
                        fields=["tenant", "content_type", "object_id", "-created_at"],
                        name="object_hist_obj_lookup",
                    ),
                    models.Index(
                        fields=["content_type", "action", "-created_at"],
                        name="object_hist_action_lookup",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="objecthistory",
            constraint=models.UniqueConstraint(
                fields=("content_type", "object_id", "version"),
                name="object_hist_unique_version",
            ),
        ),
    ]
# Generated by Django 5.2.4 on 2025-11-25 08:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_supabaseauthuser'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('object_id', models.CharField(db_index=True, max_length=64)),
                ('object_repr', models.TextField()),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted')], max_length=32)),
                ('actor_label', models.CharField(blank=True, max_length=128)),
                ('version', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('before_state', models.JSONField(blank=True, default=dict)),
                ('after_state', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_entries', to='accounts.supabaseauthuser')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
                ('tenant', models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='core.tenant')),
            ],
            options={
                'verbose_name_plural': 'Object history entries',
                'db_table': 'object_history',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['tenant', 'content_type', 'object_id', '-created_at'], name='object_hist_tenant__3787cf_idx'), models.Index(fields=['content_type', 'action', '-created_at'], name='object_hist_content_5a8354_idx')],
                'constraints': [models.UniqueConstraint(fields=('content_type', 'object_id', 'version'), name='unique_object_version')],
            },
        ),
    ]
