# Generated by Django 5.2.4 on 2025-11-25 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_supabaseauthuser'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
        ('object_history', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objecthistory',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveConstraint(
            model_name='objecthistory',
            name='unique_object_version',
        ),
        migrations.RenameIndex(
            model_name='objecthistory',
            new_name='object_hist_obj_lookup',
            old_name='object_hist_tenant__3787cf_idx',
        ),
        migrations.RenameIndex(
            model_name='objecthistory',
            new_name='object_hist_action_lookup',
            old_name='object_hist_content_5a8354_idx',
        ),
        migrations.AlterField(
            model_name='objecthistory',
            name='action',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='objecthistory',
            name='actor_label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='objecthistory',
            name='actor_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='object_history_entries', to='accounts.supabaseauthuser'),
        ),
        migrations.AlterField(
            model_name='objecthistory',
            name='after_state',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='objecthistory',
            name='before_state',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='objecthistory',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_history_entries', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='objecthistory',
            name='object_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='objecthistory',
            name='version',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddConstraint(
            model_name='objecthistory',
            constraint=models.UniqueConstraint(fields=('content_type', 'object_id', 'version'), name='object_hist_unique_version'),
        ),
    ]
