# Generated by Django 5.2.4 on 2026-04-29 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_create_auth_schema_and_users_if_missing'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0004_idle_in_transaction_session_timeout'),
        ('object_history', '0003_objecthistory_soft_delete'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='objecthistory',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='objecthistory',
            name='is_deleted',
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='objecthistory',
            index=models.Index(fields=['tenant', '-created_at'], name='object_hist_tenant__4f8dbb_idx'),
        ),
    ]
