# Generated by Django 5.2.4 on 2026-02-20 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authz', '0011_add_indexes_for_name_company_name'),
        ('core', '0001_initial'),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='role',
            field=models.ForeignKey(blank=True, db_column='role', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to='authz.role'),
        ),
        migrations.AlterField(
            model_name='page',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='core.tenant'),
        ),
    ]
