# Generated by Django 5.2.4 on 2026-02-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_page_role_alter_page_tenant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['display_order', '-updated_at']},
        ),
        migrations.AddField(
            model_name='page',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='page',
            name='header_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
