# Generated by Django 5.2.4 on 2026-02-24 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_page_options_page_display_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='icon_name',
            field=models.CharField(blank=True, default='wip tickets praja', help_text='Key matching the navigationIconMap in the frontend.', max_length=100, null=True),
        ),
    ]
