# Generated by Django 5.2.4 on 2026-03-02 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_page_icon_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='icon_name',
            field=models.CharField(blank=True, default='Sparkles', help_text='Key matching the navigationIconMap in the frontend.', max_length=100, null=True),
        ),
    ]
