# Generated by Django 5.2.4 on 2026-03-25 01:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_enable_pg_trgm'),
        ('pages', '0005_alter_page_icon_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomIcon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('svg_content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'db_table': 'custom_icons',
                'unique_together': {('tenant', 'name')},
            },
        ),
    ]
