# Generated by Django 5.2.4 on 2026-04-29 11:53
#
# No RenameIndex → avoids collisions with hashed auto-names. Base (tenant,-created_at)
# stays with explicit names from 0007; indexes match pages/models.Meta.

from django.db import migrations, models
from django.db.backends.utils import names_digest, split_identifier


def _django_field_index_relname(table: str, column: str) -> str:
    _, tbl = split_identifier(table)
    return "%s_%s_%s" % (tbl, column, names_digest(tbl, column, length=8))


def _drop_preflight_field_indexes_pg(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    qn = schema_editor.connection.ops.quote_name
    names = [
        _django_field_index_relname("custom_icons", "created_at"),
        _django_field_index_relname("custom_icons", "updated_at"),
        _django_field_index_relname("custom_icons", "is_deleted"),
        _django_field_index_relname("pages", "is_deleted"),
    ]
    with schema_editor.connection.cursor() as cursor:
        for name in names:
            cursor.execute("DROP INDEX IF EXISTS %s" % qn(name))


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_pages_soft_delete'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customicon',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelManagers(
            name='customicon',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='page',
            managers=[
            ],
        ),
        migrations.RunPython(_drop_preflight_field_indexes_pg, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='customicon',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='customicon',
            name='is_deleted',
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='customicon',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='is_deleted',
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
    ]
