# Generated by Django 5.2.4 on 2026-04-29 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_pages_soft_delete'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customicon',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelManagers(
            name='customicon',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='page',
            managers=[
            ],
        ),
        migrations.RenameIndex(
            model_name='customicon',
            new_name='custom_icon_tenant__96e99d_idx',
            old_name='custom_icons_tnt_cr_desc_idx',
        ),
        migrations.RenameIndex(
            model_name='page',
            new_name='pages_tenant__1a5bcf_idx',
            old_name='pages_tnt_cr_desc_idx',
        ),
        migrations.AlterField(
            model_name='customicon',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='customicon',
            name='is_deleted',
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='customicon',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='is_deleted',
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
    ]
