# Generated by Django 5.2.4 on 2026-06-16 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyro_jobs', '0002_pyrojob_completed_at_pyrojob_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pyrojob',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pyrojob',
            name='max_attempts',
            field=models.IntegerField(default=3),
        ),
    ]
