# Generated by Django 5.2.4 on 2025-10-23 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(help_text='The user ID this setting belongs to')),
                ('key', models.CharField(help_text="The setting key (e.g., 'LEAD_TYPE_ASSIGNMENT')", max_length=100)),
                ('value', models.JSONField(help_text="The setting value (e.g., ['LEAD_TYPE_1', 'LEAD_TYPE_2'])")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(db_column='tenant_id', help_text='The tenant this setting belongs to', on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'db_table': 'user_settings',
                'indexes': [models.Index(fields=['tenant', 'user_id'], name='user_settin_tenant__fb0e9c_idx'), models.Index(fields=['tenant', 'key'], name='user_settin_tenant__ebf4d8_idx')],
                'unique_together': {('tenant', 'user_id', 'key')},
            },
        ),
    ]
