# Generated by Django 5.2.4 on 2025-12-12 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_settings', '0002_add_assigned_leads_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='assigned_leads_count',
        ),
    ]
