# Generated by Django 5.2.4 on 2025-12-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_settings', '0003_remove_usersettings_assigned_leads_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='daily_target',
            field=models.IntegerField(blank=True, help_text='Daily target for the user', null=True),
        ),
    ]
