# Generated by Django 5.2.4 on 2025-12-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_settings", "0003_remove_usersettings_assigned_leads_count_and_more"),
    ]

    operations = [
        # Database: add ONLY daily_limit safely (daily_target already exists in DB in your environment)
        migrations.RunSQL(
            sql="""
                ALTER TABLE user_settings
                ADD COLUMN IF NOT EXISTS daily_limit integer;
            """,
            reverse_sql="""
                ALTER TABLE user_settings
                DROP COLUMN IF EXISTS daily_limit;
            """,
        ),
        # State: ensure Django model state matches DB
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                # daily_target: model already has it; we record it in migration state WITHOUT touching the DB
                migrations.AddField(
                    model_name="usersettings",
                    name="daily_target",
                    field=models.IntegerField(
                        null=True,
                        blank=True,
                        help_text="Daily target for the user",
                    ),
                ),
                # daily_limit: state matches the DB column we add above
                migrations.AddField(
                    model_name="usersettings",
                    name="daily_limit",
                    field=models.IntegerField(
                        null=True,
                        blank=True,
                        help_text="Daily lead pull limit for the user (max leads they can fetch per day)",
                    ),
                ),
            ],
        ),
    ]


