# Generated by Django 5.2.4 on 2025-12-23 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('user_settings', '0004_add_daily_target_and_daily_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(help_text='The user ID this routing rule applies to (Supabase user UUID or legacy UID)')),
                ('queue_type', models.CharField(help_text="Type of queue this rule applies to, e.g. 'ticket' or 'lead'", max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this rule is currently active')),
                ('conditions', models.JSONField(blank=True, default=dict, help_text="Simple condition config, e.g.: {'filters': [{'field': 'state', 'op': 'equals', 'value': 'Tamil Nadu'}]}")),
                ('name', models.CharField(blank=True, help_text='Optional human-readable name for this rule', max_length=255, null=True)),
                ('description', models.TextField(blank=True, help_text='Optional description for this rule', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(db_column='tenant_id', help_text='The tenant this routing rule belongs to', on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'db_table': 'routing_rules',
                'indexes': [models.Index(fields=['tenant', 'queue_type', 'user_id'], name='routing_rul_tenant__80c28d_idx'), models.Index(fields=['tenant', 'queue_type', 'is_active'], name='routing_rul_tenant__3dd449_idx')],
                'unique_together': {('tenant', 'user_id', 'queue_type')},
            },
        ),
    ]
