# Generated by Django 5.2.4 on 2026-01-06 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_settings', '0005_change_user_id_to_tenant_membership_fk'),
        ('user_settings', '0005_routingrule'),
    ]

    operations = [
    ]
