# Generated by Django 5.2.4 on 2026-01-16 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_settings', '0006_merge_20260106_1145'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='usersettings',
            new_name='user_settin_tenant__c5a5e4_idx',
            old_name='user_settin_tenant__tenant_m_idx',
        ),
        migrations.AlterField(
            model_name='routingrule',
            name='user_id',
            field=models.UUIDField(help_text='The user ID this routing rule applies to (Supabase user UUID)'),
        ),
    ]
