# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_settings", "0007_rename_user_settin_tenant__tenant_m_idx_user_settin_tenant__c5a5e4_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="lead_sources",
            field=models.JSONField(
                blank=True,
                help_text="List of lead sources assigned to this user (for key=LEAD_TYPE_ASSIGNMENT); only these leads are directed to the RM",
                null=True,
            ),
        ),
    ]
