# Generated by Django 5.2.4 on 2026-02-06 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authz', '0008_change_user_parent_id_to_foreignkey'),
        ('user_settings', '0010_routingrule_tenant_membership'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='routingrule',
            new_name='routing_rul_tenant__7b2f52_idx',
            old_name='routing_rul_tenant__tm_idx',
        ),
        migrations.AlterField(
            model_name='routingrule',
            name='tenant_membership',
            field=models.ForeignKey(db_column='tenant_membership_id', help_text='The tenant membership this rule applies to (primary key for the rule).', on_delete=django.db.models.deletion.CASCADE, to='authz.tenantmembership'),
        ),
        migrations.AlterField(
            model_name='routingrule',
            name='user_id',
            field=models.UUIDField(blank=True, help_text='Denormalized from TenantMembership.user_id when set; may be null if membership has no linked auth user yet.', null=True),
        ),
    ]
