# Generated by Django 5.2.4 on 2026-04-29 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_settings', '0017_user_settings_soft_delete'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='routingrule',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='tenantmembersetting',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='usersettings',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelManagers(
            name='group',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='routingrule',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='tenantmembersetting',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='usersettings',
            managers=[
            ],
        ),
        migrations.RenameIndex(
            model_name='group',
            new_name='groups_tenant__01acbe_idx',
            old_name='groups_tnt_cr_idx',
        ),
        migrations.RenameIndex(
            model_name='group',
            new_name='groups_tenant__fbdd57_idx',
            old_name='groups_tenant__95f522_idx',
        ),
        migrations.RenameIndex(
            model_name='routingrule',
            new_name='routing_rul_tenant__3ca5c8_idx',
            old_name='routing_rul_tnt_cr_idx',
        ),
        migrations.RenameIndex(
            model_name='tenantmembersetting',
            new_name='user_kv_set_tenant__5468da_idx',
            old_name='user_kv_set_tnt_cr_idx',
        ),
        migrations.RenameIndex(
            model_name='tenantmembersetting',
            new_name='user_kv_set_tenant__b8dc9e_idx',
            old_name='user_kv_set_tenant__f8f0c6_idx',
        ),
        migrations.RenameIndex(
            model_name='tenantmembersetting',
            new_name='user_kv_set_tenant__01c553_idx',
            old_name='user_kv_set_tenant__533788_idx',
        ),
        migrations.RenameIndex(
            model_name='usersettings',
            new_name='user_settin_tenant__c6f569_idx',
            old_name='user_settin_tnt_cr_idx',
        ),
        migrations.AlterField(
            model_name='group',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='is_deleted',
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='group',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='routingrule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='routingrule',
            name='is_deleted',
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='routingrule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='tenantmembersetting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='tenantmembersetting',
            name='is_deleted',
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='tenantmembersetting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='is_deleted',
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
