# Generated by Django 5.2.4 on 2026-09-24 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authz', '0018_add_analytics_membership_indexes'),
        ('core', '0011_drop_tenant_users_and_party'),
        ('user_settings', '0020_add_records_assigned_to_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='RmDailyTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_default=False, db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('date', models.DateField(help_text='Calendar date this target applies to')),
                ('target', models.PositiveIntegerField(help_text='Trial target for this RM on this date')),
                ('tenant', models.ForeignKey(db_column='tenant_id', help_text='The tenant this target belongs to', on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
                ('tenant_membership', models.ForeignKey(db_column='tenant_membership_id', help_text='The RM this target is for', on_delete=django.db.models.deletion.CASCADE, to='authz.tenantmembership')),
            ],
            options={
                'db_table': 'rm_daily_targets',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['tenant', '-created_at'], name='rm_daily_ta_tenant__5947e3_idx'), models.Index(fields=['tenant', 'tenant_membership', 'date'], name='rm_daily_ta_tenant__98137d_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('deleted_at__isnull', True)), fields=('tenant', 'tenant_membership', 'date'), name='rm_daily_targets_tenant_mship_date_uniq_alive')],
            },
        ),
    ]
