# Generated by Django 5.2.4 on 2025-08-06 18:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicketDump',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('ticket_date', models.DateTimeField(blank=True, null=True)),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('subscription_status', models.TextField(blank=True, null=True)),
                ('atleast_paid_once', models.BooleanField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('badge', models.CharField(blank=True, max_length=255, null=True)),
                ('poster', models.CharField(blank=True, max_length=255, null=True)),
                ('tenant_id', models.UUIDField(blank=True, null=True)),
                ('assigned_to', models.UUIDField(blank=True, null=True)),
                ('layout_status', models.CharField(blank=True, max_length=255, null=True)),
                ('resolution_status', models.CharField(blank=True, max_length=255, null=True)),
                ('resolution_time', models.TextField(blank=True, null=True)),
                ('cse_name', models.CharField(blank=True, max_length=255, null=True)),
                ('cse_remarks', models.TextField(blank=True, null=True)),
                ('call_status', models.CharField(blank=True, max_length=255, null=True)),
                ('call_attempts', models.IntegerField(blank=True, null=True)),
                ('rm_name', models.TextField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('snooze_until', models.DateTimeField(blank=True, null=True)),
                ('dumped_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('praja_dashboard_user_link', models.TextField(blank=True, null=True)),
                ('display_pic_url', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'support_ticket_dump',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant_id'], name='support_tic_tenant__d01072_idx'), models.Index(fields=['is_processed'], name='support_tic_is_proc_8526f7_idx'), models.Index(fields=['created_at'], name='support_tic_created_7febc3_idx')],
            },
        ),
    ]
