"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
import environ
from corsheaders.defaults import default_headers

env = environ.Env()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
environ.Env.read_env(os.path.join(BASE_DIR.parent, '.env'))

DJANGO_ENV = os.getenv("DJANGO_ENV", "development").lower()

IS_DEV = DJANGO_ENV == "development"
IS_STAGING = DJANGO_ENV == "staging"
IS_PROD = DJANGO_ENV == "production"

if os.environ.get("RUN_MAIN") == "true":
    print("Server Type -", DJANGO_ENV)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("DJANGO_SECRET_KEY")
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = IS_DEV or IS_STAGING

ALLOWED_HOSTS = (
    ["*"] if IS_DEV else  # local convenience
    ["pyro-backend-1.onrender.com"] if IS_STAGING else
    ["pyro-prod-backend.onrender.com"]
)
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    "drf_spectacular",
    "drf_spectacular_sidecar",
    "django_filters",
    'authentication',
    'authz',
    'corsheaders',
    'analytics',
    'cron_jobs',
    'crm',
    'crm_records',
    'core',
    'scheduler',
    'accounts',
    'support_ticket',
    'user_settings',
    'openai_api',
    'email_protocol'
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'middleware.tenant.TenantResolver', 
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Logging might add color later for better debugging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {name} {funcName} - {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        # will add file logging in future
    },
    'root': {
        'handlers': ['console'],  
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'api': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

if env.bool("LOCAL_TEST_MODE", default=False):
    # print("Using local db")
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': env("LOCAL_DB_NAME"),
            'USER': env("LOCAL_DB_USER"),
            'PASSWORD': env("LOCAL_DB_PASSWORD"),
            'HOST': env("LOCAL_DB_HOST"),
            'PORT': env("LOCAL_DB_PORT"),
        }
    }
else:
    # print("Using supabase db")
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': env("DB_NAME"),
            'USER': env("DB_USER"),
            'PASSWORD': env("DB_PASSWORD"),
            'HOST': env("DB_HOST"),
            'PORT': env("DB_PORT"),
            'OPTIONS': {
                'sslmode': 'require',
            },
            'CONN_MAX_AGE': 120,  # Keep connections alive for 5 minutes
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOW_ALL_ORIGINS = True # for dev only not to be added in prod


# CORS_ALLOWED_ORIGINS = [
#     # Production frontend to be added in the list
#     "http://localhost:3000",         # Local development (React)
# ]

AUTH_USER_MODEL = 'authentication.User'
SUPABASE_JWT_SECRET = env("SUPABASE_JWT_SECRET")

# Praja secret for external API access (used in X-Secret-Praja header)
PRAJA_SECRET = env("PRAJA_SECRET", default="")

REST_FRAMEWORK = {
    # Enable API-wide permissions
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',  # Only authenticated users by default
    ],

    # Exception handling (optional: improves error responses)
    'EXCEPTION_HANDLER': 'rest_framework.views.exception_handler',
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'config.supabase_auth.SupabaseJWTAuthentication',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

if DEBUG:
    REST_FRAMEWORK["DEFAULT_RENDERER_CLASSES"] = [
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    ]
else:
    REST_FRAMEWORK["DEFAULT_RENDERER_CLASSES"] = [
        "rest_framework.renderers.JSONRenderer",
]


SPECTACULAR_SETTINGS = {
    "TITLE": "Pyro Endpoints",
    "DESCRIPTION": "",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": True,
    "SERVE_PUBLIC": True,         
    "SWAGGER_UI_SETTINGS": {"persistAuthorization": True},

    "SECURITY_SCHEMES": {
        "BearerAuth": {
            "type": "http",
            "scheme": "bearer",
            "bearerFormat": "JWT",
        },
    },
    
    "SECURITY": [{"BearerAuth": []}],
    "COMPONENT_SPLIT_REQUEST": True,
}


SENTRY_DSN = os.getenv("SENTRY_DSN", "")

# Staging environment flag - used to control certain behaviors like assigned_to field updates
IS_STAGING_ENV = os.getenv("IS_STAGING_ENV", "false").lower() == "true"

if not IS_DEV and SENTRY_DSN:
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration
    sentry_sdk.init(
    dsn=SENTRY_DSN,
    environment=DJANGO_ENV,
    integrations=[DjangoIntegration()],
    send_default_pii=False,
    traces_sampler=lambda _: 1.0,   # capture all requests
    profiles_sample_rate=1.0,       # profile every request
)



TENANCY_BASE_DOMAIN = os.environ.get("TENANCY_BASE_DOMAIN")      # e.g. "api.example.com"
DEFAULT_TENANT_SLUG = os.environ.get("DEFAULT_TENANT_SLUG")      # e.g. "dev" (dev-only)


if IS_DEV:
    CORS_ALLOW_ALL_ORIGINS = True
    CORS_ALLOWED_ORIGINS = []
else:
    # Staging / Production: strict origins
    CORS_ALLOW_ALL_ORIGINS = False
    CORS_ALLOWED_ORIGINS = env.list(
        "CORS_ALLOWED_ORIGINS",
        default=[
            # Staging frontend
            "https://staging.thepyro.ai",
            # Prod frontend
            "https://app.thepyro.ai",
        ] if IS_STAGING else [
            # Only production frontend
            "https://app.thepyro.ai",
        ]
    )

CORS_ALLOW_HEADERS = list(default_headers) + [
    "X-Tenant-Slug",  # custom tenant header
    "X-Secret-Praja",  # Praja API secret header
]

# Email configuration
# Use custom backend for better SSL handling
# Check if EMAIL_BACKEND is explicitly set in env, otherwise use our custom backend
if 'EMAIL_BACKEND' in os.environ:
    EMAIL_BACKEND = env('EMAIL_BACKEND')
    print(f"Using EMAIL_BACKEND from environment: {EMAIL_BACKEND}")
else:
    EMAIL_BACKEND = 'email_protocol.backends.CustomSMTPBackend'
    print(f"Using default custom EMAIL_BACKEND: {EMAIL_BACKEND}")
EMAIL_HOST = env('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = env.int('EMAIL_PORT', default=587)
EMAIL_USE_TLS = env.bool('EMAIL_USE_TLS', default=True)
EMAIL_USE_SSL = env.bool('EMAIL_USE_SSL', default=False)
EMAIL_HOST_USER = env('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', default=EMAIL_HOST_USER)

# SSL Certificate verification (set to False for development if having SSL issues)
# WARNING: Only disable in development, never in production!
EMAIL_SSL_VERIFY = env.bool('EMAIL_SSL_VERIFY', default=not IS_DEV)  # Disable in dev by default

import config.spectacular_auth