# Generated by Django 5.2.4 on 2026-07-31 11:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0008_alter_recordaggregator_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('is_deleted', models.BooleanField(db_default=False, db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True, help_text='Supabase auth user id who owns this conversation.')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('tenant', models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='core.tenant')),
            ],
            options={
                'db_table': 'chatbot_conversations',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('is_deleted', models.BooleanField(db_default=False, db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=128)),
                ('title', models.CharField(max_length=255)),
                ('domain', models.CharField(db_index=True, default='general', help_text='crm | erp | general', max_length=32)),
                ('source_path', models.CharField(blank=True, default='', max_length=512)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('tenant', models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='core.tenant')),
            ],
            options={
                'db_table': 'chatbot_knowledge_documents',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('is_deleted', models.BooleanField(db_default=False, db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_index', models.PositiveIntegerField(default=0)),
                ('content', models.TextField()),
                ('embedding', models.JSONField(blank=True, default=list, help_text='Vector embedding as a list of floats.')),
                ('token_count', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('tenant', models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='core.tenant')),
                ('document', models.ForeignKey(db_column='document_id', on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='chatbot.knowledgedocument')),
            ],
            options={
                'db_table': 'chatbot_knowledge_chunks',
                'ordering': ['document', 'chunk_index'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('is_deleted', models.BooleanField(db_default=False, db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System'), ('tool', 'Tool')], db_index=True, max_length=16)),
                ('content', models.TextField(blank=True, default='')),
                ('mode', models.CharField(blank=True, default='', help_text='rag | tools | hybrid | clarify', max_length=32)),
                ('sources', models.JSONField(blank=True, default=list)),
                ('tool_calls', models.JSONField(blank=True, default=list)),
                ('page_context', models.JSONField(blank=True, default=dict)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('conversation', models.ForeignKey(db_column='conversation_id', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.conversation')),
                ('tenant', models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='core.tenant')),
            ],
            options={
                'db_table': 'chatbot_messages',
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['tenant', '-created_at'], name='chatbot_con_tenant__5d8ba6_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['tenant', 'user_id', '-updated_at'], name='chatbot_con_tenant__6e647d_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgedocument',
            index=models.Index(fields=['tenant', '-created_at'], name='chatbot_kno_tenant__69a369_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgedocument',
            index=models.Index(fields=['domain', 'slug'], name='chatbot_kno_domain_df1d5b_idx'),
        ),
        migrations.AddConstraint(
            model_name='knowledgedocument',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('deleted_at__isnull', True), ('tenant__isnull', True)), fields=('slug',), name='chatbot_knowledgedoc_global_slug_uniq_alive'),
        ),
        migrations.AddConstraint(
            model_name='knowledgedocument',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('deleted_at__isnull', True), ('tenant__isnull', False)), fields=('tenant', 'slug'), name='chatbot_knowledgedoc_tenant_slug_uniq_alive'),
        ),
        migrations.AddIndex(
            model_name='knowledgechunk',
            index=models.Index(fields=['tenant', '-created_at'], name='chatbot_kno_tenant__32bc51_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgechunk',
            index=models.Index(fields=['document', 'chunk_index'], name='chatbot_kno_documen_dcf2de_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['tenant', '-created_at'], name='chatbot_mes_tenant__ba40f7_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='chatbot_mes_convers_9b53f8_idx'),
        ),
    ]
