# Generated by Django 5.2.4 on 2025-08-14 11:10

import django.core.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('slug', models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(regex='^[a-z0-9]+(-[a-z0-9]+)*$')])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'tenants',
                'managed': False,
            },
        ),
    ]
