# Generated by Django 5.2.4 on 2025-08-14 11:10

import django.core.validators
import django.utils.timezone
import uuid
from django.db import migrations, models

CREATE_PG_TRGM = "CREATE EXTENSION IF NOT EXISTS pg_trgm;"

CREATE_TENANTS_IF_MISSING = """
CREATE TABLE IF NOT EXISTS public.tenants (
    id UUID NOT NULL PRIMARY KEY,
    name TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    slug VARCHAR(64) NOT NULL UNIQUE
);
"""


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(CREATE_PG_TRGM, reverse_sql="DROP EXTENSION IF EXISTS pg_trgm;"),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('slug', models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(regex='^[a-z0-9]+(-[a-z0-9]+)*$')])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'tenants',
                'managed': False,
            },
        ),
        migrations.RunSQL(
            CREATE_TENANTS_IF_MISSING,
            reverse_sql="DROP TABLE IF EXISTS public.tenants;",
        ),
    ]
