# Generated by Django 5.2.4 on 2026-04-21 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_idle_in_transaction_session_timeout'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('setting_key', models.CharField(db_index=True, help_text="Unique key for this setting (e.g., 'record_aggregator_last_processed_id')", max_length=255, unique=True)),
                ('setting_value', models.JSONField(default=dict, help_text='JSON value for this setting')),
                ('description', models.TextField(blank=True, help_text='Description of what this setting is for')),
            ],
            options={
                'verbose_name_plural': 'System Settings',
                'db_table': 'system_settings',
                'indexes': [models.Index(fields=['setting_key'], name='system_sett_setting_420d58_idx')],
            },
        ),
        migrations.CreateModel(
            name='RecordAggregator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('entity_type', models.CharField(db_index=True, help_text="Entity type (e.g., 'lead', 'invoice', 'inventory_item')", max_length=100)),
                ('schema_snapshot', models.JSONField(default=dict, help_text='Schema snapshot: {field_name: {count, field_type}}')),
                ('total_records_processed', models.BigIntegerField(default=0, help_text='Total records processed for this entity type')),
                ('last_aggregation_at', models.DateTimeField(blank=True, help_text='Timestamp of last aggregation run', null=True)),
                ('tenant', models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='core.tenant')),
            ],
            options={
                'db_table': 'record_aggregators',
                'indexes': [models.Index(fields=['tenant', 'entity_type'], name='record_aggr_tenant__54ce58_idx'), models.Index(fields=['tenant', '-last_aggregation_at'], name='record_aggr_tenant__ed23d2_idx')],
                'unique_together': {('tenant', 'entity_type')},
            },
        ),
    ]
