# Generated by Django 5.2.4 on 2026-04-27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_systemsettings_recordaggregator'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecordAggregator',
        ),
        migrations.DeleteModel(
            name='SystemSettings',
        ),
    ]