# Generated by Django 5.2.4 on 2026-06-16 11:35

from django.db import migrations, models


def _index_exists(cursor, name: str) -> bool:
    cursor.execute(
        "SELECT 1 FROM pg_indexes WHERE schemaname = current_schema() AND indexname = %s LIMIT 1",
        [name],
    )
    return cursor.fetchone() is not None


def _rename_index_if_needed(cursor, old_name: str, new_name: str) -> None:
    if _index_exists(cursor, old_name) and not _index_exists(cursor, new_name):
        cursor.execute(f'ALTER INDEX "{old_name}" RENAME TO "{new_name}"')


def drop_legacy_core_tables(apps, schema_editor):
    """Drop removed models without assuming prior unique_together exists."""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("DROP TABLE IF EXISTS record_aggregators CASCADE")
        cursor.execute("DROP TABLE IF EXISTS system_settings CASCADE")


def apply_tenant_entity_type_db_changes(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            "ALTER TABLE tenant_entity_types "
            "DROP CONSTRAINT IF EXISTS tenant_entity_types_tenant_entity_type_uniq_alive"
        )
        _rename_index_if_needed(cursor, "tenant_enti_tenant__88f4bf_idx", "tenant_enti_tenant__633828_idx")
        _rename_index_if_needed(cursor, "tenant_enti_tenant__6d9c64_idx", "tenant_enti_tenant__471a33_idx")
        _rename_index_if_needed(cursor, "tenant_enti_tenant__189b55_idx", "tenant_enti_tenant__43190d_idx")
        cursor.execute(
            "ALTER TABLE tenant_entity_types ALTER COLUMN is_deleted SET DEFAULT false"
        )
        cursor.execute(
            """
            CREATE UNIQUE INDEX IF NOT EXISTS tenant_entity_types_tenant_entity_type_uniq_alive
            ON tenant_entity_types (tenant_id, entity_type)
            WHERE is_deleted = false AND deleted_at IS NULL
            """
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_entity_type_discovery'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='recordaggregator',
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name='recordaggregator',
                    name='tenant',
                ),
                migrations.DeleteModel(
                    name='RecordAggregator',
                ),
                migrations.DeleteModel(
                    name='SystemSettings',
                ),
            ],
            database_operations=[
                migrations.RunPython(drop_legacy_core_tables, noop_reverse),
            ],
        ),
        migrations.AlterModelOptions(
            name='tenantentitytype',
            options={'ordering': ['-created_at']},
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveConstraint(
                    model_name='tenantentitytype',
                    name='tenant_entity_types_tenant_entity_type_uniq_alive',
                ),
                migrations.RenameIndex(
                    model_name='tenantentitytype',
                    new_name='tenant_enti_tenant__633828_idx',
                    old_name='tenant_enti_tenant__88f4bf_idx',
                ),
                migrations.RenameIndex(
                    model_name='tenantentitytype',
                    new_name='tenant_enti_tenant__471a33_idx',
                    old_name='tenant_enti_tenant__6d9c64_idx',
                ),
                migrations.RenameIndex(
                    model_name='tenantentitytype',
                    new_name='tenant_enti_tenant__43190d_idx',
                    old_name='tenant_enti_tenant__189b55_idx',
                ),
                migrations.AlterField(
                    model_name='tenantentitytype',
                    name='is_deleted',
                    field=models.BooleanField(db_default=False, db_index=True, default=False),
                ),
                migrations.AddConstraint(
                    model_name='tenantentitytype',
                    constraint=models.UniqueConstraint(
                        condition=models.Q(('deleted_at__isnull', True), ('is_deleted', False)),
                        fields=('tenant', 'entity_type'),
                        name='tenant_entity_types_tenant_entity_type_uniq_alive',
                    ),
                ),
            ],
            database_operations=[
                migrations.RunPython(apply_tenant_entity_type_db_changes, noop_reverse),
            ],
        ),
    ]
