# Generated by Django 5.2.4 on 2026-07-31 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_recordaggregator_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantsettings',
            name='chatbot_page_owner_email',
            field=models.EmailField(blank=True, help_text='Email of the membership that owns pages created via the AI chatbot. Must match an active tenant membership with a linked user_id. Falls back to env CHATBOT_PAGE_OWNER_EMAIL if empty.', max_length=254, null=True),
        ),
    ]
