# Generated by Django 5.2.4 on 2026-08-25 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0011_drop_tenant_users_and_party'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZohoMailConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('email_address', models.EmailField(blank=True, default='', max_length=254)),
                ('account_id', models.CharField(blank=True, default='', max_length=64)),
                ('inbox_folder_id', models.CharField(blank=True, default='', max_length=64)),
                ('refresh_token', models.TextField()),
                ('access_token', models.TextField(blank=True, default='')),
                ('access_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('accounts_base_url', models.URLField(default='https://accounts.zoho.com', help_text='e.g. https://accounts.zoho.com or https://accounts.zoho.in', max_length=255)),
                ('mail_api_base_url', models.URLField(default='https://mail.zoho.com/api', help_text='e.g. https://mail.zoho.com/api or https://mail.zoho.in/api', max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_received_time_ms', models.BigIntegerField(blank=True, null=True)),
                ('connected_by_email', models.EmailField(blank=True, default='', max_length=254)),
                ('tenant', models.OneToOneField(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='zoho_mail_connection', to='core.tenant')),
            ],
            options={
                'db_table': 'email_protocol_zoho_mail_connection',
            },
        ),
        migrations.CreateModel(
            name='ZohoMailProcessedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('message_id', models.CharField(db_index=True, max_length=64)),
                ('subject', models.CharField(blank=True, default='', max_length=512)),
                ('matched_record_id', models.UUIDField(blank=True, null=True)),
                ('applied', models.BooleanField(default=False)),
                ('skip_reason', models.CharField(blank=True, default='', max_length=255)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_messages', to='email_protocol.zohomailconnection')),
            ],
            options={
                'db_table': 'email_protocol_zoho_mail_processed_message',
                'constraints': [models.UniqueConstraint(fields=('connection', 'message_id'), name='uniq_zoho_mail_processed_message')],
            },
        ),
    ]
