# Generated by Django 5.2.4 on 2026-10-08 11:48

import django.db.models.functions.text
from django.db import migrations, models
from django.db.models import Count
from django.db.models.functions import Lower


def refuse_duplicate_emails(apps, schema_editor):
    User = apps.get_model("authentication", "User")
    duplicates = list(
        User.objects.exclude(email__isnull=True)
        .exclude(email="")
        .annotate(email_key=Lower("email"))
        .values("email_key")
        .annotate(n=Count("id"))
        .filter(n__gt=1)
        .order_by("email_key")
        .values_list("email_key", "n")
    )
    if duplicates:
        listed = "\n".join(f"  {email} ({n} accounts)" for email, n in duplicates)
        raise RuntimeError(
            f"{len(duplicates)} email address(es) belong to more than one user:\n{listed}\n"
            "Decide which account to keep for each (python manage.py find_duplicate_user_emails "
            "shows the details), fix them, then run migrate again."
        )


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentication', '0006_oauth_identities'),
    ]

    operations = [
        migrations.RunPython(refuse_duplicate_emails, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), condition=models.Q(('email__isnull', False), models.Q(('email', ''), _negated=True)), name='auth_user_email_ci_unique'),
        ),
    ]
