# Generated by Django 5.2.4 on 2025-08-11 08:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsRunCore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user_id', models.CharField(db_index=True, max_length=128)),
                ('question', models.TextField()),
                ('sql_query', models.TextField(blank=True, null=True)),
                ('validation_ok', models.BooleanField(default=False)),
                ('validation_reason', models.TextField(blank=True, null=True)),
                ('execution_ok', models.BooleanField(default=False)),
                ('final_result', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(db_index=True, default='started', max_length=32)),
                ('error_summary', models.TextField(blank=True, null=True)),
                ('rows_returned', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='analytics_a_created_0c735a_idx'), models.Index(fields=['user_id', 'created_at'], name='analytics_a_user_id_b6dd00_idx'), models.Index(fields=['status'], name='analytics_a_status_1ea25c_idx')],
            },
        ),
    ]
