# Generated by Django 5.2.4 on 2025-09-12 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_supportticket_st_assigned_to_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supportticket',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='supportticket',
            name='st_assigned_to_idx',
        ),
        migrations.RemoveIndex(
            model_name='supportticket',
            name='st_poster_idx',
        ),
        migrations.RemoveIndex(
            model_name='supportticket',
            name='st_res_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='supportticket',
            name='st_tenant_assigned_idx',
        ),
        migrations.RemoveIndex(
            model_name='supportticket',
            name='st_tenant_poster_idx',
        ),
        migrations.RemoveIndex(
            model_name='supportticket',
            name='st_tenant_res_idx',
        ),
        migrations.AlterModelTable(
            name='supportticket',
            table=None,
        ),
    ]
