# Generated by Django 5.2.4 on 2025-09-12 13:27

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_alter_supportticket_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supportticket',
            options={'managed': True},
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['tenant_id', '-created_at'], name='st_tn_cr_desc'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['tenant_id', 'resolution_status', '-created_at'], name='st_tn_res_cr'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['tenant_id', 'poster', '-created_at'], name='st_tn_pst_cr'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['tenant_id', 'assigned_to', '-created_at'], name='st_tn_asg_cr'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(condition=models.Q(('assigned_to__isnull', True)), fields=['tenant_id', '-created_at'], name='st_tn_asg_null_cr'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(condition=models.Q(('poster__isnull', True)), fields=['tenant_id', '-created_at'], name='st_tn_pst_null_cr'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='st_name_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=django.contrib.postgres.indexes.GinIndex(fields=['phone'], name='st_phone_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=django.contrib.postgres.indexes.GinIndex(fields=['user_id'], name='st_uid_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created_at'], name='st_brin_cr'),
        ),
        migrations.AlterModelTable(
            name='supportticket',
            table='support_ticket',
        ),
    ]
