# Generated by Django 5.2.4 on 2025-09-29 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_enable_pg_trgm'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='review_requested',
            field=models.BooleanField(blank=True, help_text='Whether CSE requested customer to post a review', null=True),
        ),
    ]
