# Generated by Django 5.2.4 on 2025-09-25 13:33

from django.db import migrations

class Migration(migrations.Migration):
    dependencies = [
        ('support_ticket', '0001_supportticket_state'), 
        ('analytics', '0006_enable_pg_trgm'),
    ]
    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[migrations.DeleteModel(name='SupportTicket')],
            database_operations=[],  # NO DB DROP
        ),
    ]
