# Generated by Django 5.2.4 on 2026-04-29 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_analyticsruncore_basemodel_fields'),
        ('core', '0004_idle_in_transaction_session_timeout'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='analyticsruncore',
            managers=[
            ],
        ),
        migrations.RenameIndex(
            model_name='analyticsruncore',
            new_name='analytics_a_tenant__e5e9e4_idx',
            old_name='analytics_a_tnt_cr_idx',
        ),
        migrations.AlterField(
            model_name='analyticsruncore',
            name='is_deleted',
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='analyticsruncore',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='core.tenant'),
        ),
        migrations.AlterField(
            model_name='analyticsruncore',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
