# Generated by Django 5.2.4 on 2026-07-13 10:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0009_alter_analyticsruncore_managers_and_more'),
        ('core', '0008_alter_recordaggregator_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsBoard',
            fields=[
                ('is_deleted', models.BooleanField(db_default=False, db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, max_length=128)),
                ('board_type', models.CharField(db_index=True, default='cse', help_text="Analytics type this board belongs to, e.g. 'cse', 'rm'.", max_length=64)),
                ('key', models.CharField(default='default', help_text='Board identifier within a type (e.g. the component title).', max_length=128)),
                ('config', models.JSONField(blank=True, default=list, help_text='List of report cards saved on the board.')),
                ('tenant', models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='core.tenant')),
            ],
            options={
                'db_table': 'analytics_boards',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['tenant', '-created_at'], name='analytics_b_tenant__4b319f_idx'), models.Index(fields=['tenant', 'user_id', 'board_type', 'key'], name='analytics_b_tenant__337fa5_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('deleted_at__isnull', True)), fields=('tenant', 'user_id', 'board_type', 'key'), name='analytics_board_tenant_user_type_key_uniq_alive')],
            },
        ),
    ]
