# Generated by Django 5.2.4 on 2026-07-13 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0010_analyticsboard'),
        ('core', '0008_alter_recordaggregator_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='analyticsboard',
            name='analytics_board_tenant_user_type_key_uniq_alive',
        ),
        migrations.RemoveIndex(
            model_name='analyticsboard',
            name='analytics_b_tenant__337fa5_idx',
        ),
        migrations.RemoveField(
            model_name='analyticsboard',
            name='key',
        ),
        migrations.AddField(
            model_name='analyticsboard',
            name='report_id',
            field=models.CharField(db_index=True, default='', help_text='Frontend-generated identifier for this board/report.', max_length=128),
        ),
        migrations.AlterField(
            model_name='analyticsboard',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text="This board's definition (title, chart type, metrics, filters)."),
        ),
        migrations.AddIndex(
            model_name='analyticsboard',
            index=models.Index(fields=['tenant', 'user_id', 'board_type'], name='analytics_b_tenant__8e06d0_idx'),
        ),
        migrations.AddConstraint(
            model_name='analyticsboard',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('deleted_at__isnull', True)), fields=('tenant', 'user_id', 'board_type', 'report_id'), name='analytics_board_tenant_user_type_report_uniq_alive'),
        ),
    ]
