# Generated by Django 5.2.4 on 2026-07-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0011_remove_analyticsboard_analytics_board_tenant_user_type_key_uniq_alive_and_more'),
        ('core', '0008_alter_recordaggregator_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='analyticsboard',
            name='analytics_board_tenant_user_type_report_uniq_alive',
        ),
        migrations.RemoveIndex(
            model_name='analyticsboard',
            name='analytics_b_tenant__8e06d0_idx',
        ),
        migrations.AddField(
            model_name='analyticsboard',
            name='role',
            field=models.CharField(db_index=True, default='', help_text="Role key that shares this board, e.g. 'GM', 'ASM', 'CSE'.", max_length=64),
        ),
        migrations.AlterField(
            model_name='analyticsboard',
            name='user_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='User who created the board (informational only).', max_length=128),
        ),
        migrations.AddIndex(
            model_name='analyticsboard',
            index=models.Index(fields=['tenant', 'role', 'board_type'], name='analytics_b_tenant__4d9d8a_idx'),
        ),
        migrations.AddConstraint(
            model_name='analyticsboard',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('deleted_at__isnull', True)), fields=('tenant', 'role', 'board_type', 'report_id'), name='analytics_board_tenant_role_type_report_uniq_alive'),
        ),
    ]
