# Generated by Django 5.2.4 on 2026-07-21 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0012_remove_analyticsboard_analytics_board_tenant_user_type_report_uniq_alive_and_more'),
        ('core', '0008_alter_recordaggregator_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='analyticsboard',
            name='analytics_board_tenant_role_type_report_uniq_alive',
        ),
        migrations.RemoveIndex(
            model_name='analyticsboard',
            name='analytics_b_tenant__4d9d8a_idx',
        ),
        migrations.RemoveField(
            model_name='analyticsboard',
            name='role',
        ),
        migrations.AlterField(
            model_name='analyticsboard',
            name='user_id',
            field=models.CharField(db_index=True, help_text='User who owns this board; only they can see it.', max_length=128),
        ),
        migrations.AddIndex(
            model_name='analyticsboard',
            index=models.Index(fields=['tenant', 'user_id', 'board_type'], name='analytics_b_tenant__8e06d0_idx'),
        ),
        migrations.AddConstraint(
            model_name='analyticsboard',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('deleted_at__isnull', True)), fields=('tenant', 'user_id', 'board_type', 'report_id'), name='analytics_board_tenant_user_type_report_uniq_alive'),
        ),
    ]
