# Generated by Django 5.2.4 on 2026-09-15 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0013_repair_analyticsboard_role_column'),
        ('core', '0011_drop_tenant_users_and_party'),
        ('crm_records', '0040_backfill_network_density_pull_strategy'),
    ]

    operations = [
        migrations.CreateModel(
            name='RmActivityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_default=False, db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('rm_user_id', models.UUIDField(db_index=True, help_text='Supabase user id of the RM this event belongs to.')),
                ('rm_name', models.CharField(blank=True, default='', max_length=255)),
                ('manager_name', models.CharField(blank=True, default='', max_length=255)),
                ('team', models.CharField(blank=True, default='', max_length=255)),
                ('state', models.CharField(blank=True, default='', max_length=64)),
                ('event_type', models.CharField(choices=[('CALL_TOUCH', 'Call touch'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('BREAK_START', 'Break start'), ('BREAK_END', 'Break end')], db_index=True, max_length=20)),
                ('disposition', models.CharField(blank=True, choices=[('NOT_CONNECTED', 'Not connected'), ('CALL_BACK', 'Call back'), ('NOT_INTERESTED', 'Not interested'), ('TRIAL_ACTIVATED', 'Trial activated')], max_length=20, null=True)),
                ('lead_bucket', models.CharField(blank=True, max_length=64, null=True)),
                ('party', models.CharField(blank=True, max_length=64, null=True)),
                ('started_at', models.DateTimeField(db_index=True)),
                ('ended_at', models.DateTimeField(blank=True, help_text='Null means still in progress right now.', null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('lead_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rm_activity_events', to='crm_records.record')),
                ('tenant', models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='core.tenant')),
            ],
            options={
                'db_table': 'rm_activity_events',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['tenant', '-created_at'], name='rm_activity_tenant__8b53e1_idx'), models.Index(fields=['tenant', 'rm_user_id', '-started_at'], name='rm_events_tenant_rm_time_idx'), models.Index(fields=['tenant', 'event_type', 'disposition'], name='rm_events_disposition_idx')],
            },
        ),
    ]
