# Generated by Django 5.2.4 on 2026-09-16 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0014_rm_activity_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='rmactivityevent',
            name='event_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
