# Generated by Django 5.2.4 on 2026-09-16 12:13

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0016_backfill_rm_activity_event_data'),
        ('core', '0011_drop_tenant_users_and_party'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='rmactivityevent',
            name='rm_events_tenant_rm_time_idx',
        ),
        migrations.RemoveIndex(
            model_name='rmactivityevent',
            name='rm_events_disposition_idx',
        ),
        migrations.RemoveField(
            model_name='rmactivityevent',
            name='disposition',
        ),
        migrations.RemoveField(
            model_name='rmactivityevent',
            name='duration_seconds',
        ),
        migrations.RemoveField(
            model_name='rmactivityevent',
            name='ended_at',
        ),
        migrations.RemoveField(
            model_name='rmactivityevent',
            name='lead_bucket',
        ),
        migrations.RemoveField(
            model_name='rmactivityevent',
            name='lead_record',
        ),
        migrations.RemoveField(
            model_name='rmactivityevent',
            name='manager_name',
        ),
        migrations.RemoveField(
            model_name='rmactivityevent',
            name='party',
        ),
        migrations.RemoveField(
            model_name='rmactivityevent',
            name='rm_name',
        ),
        migrations.RemoveField(
            model_name='rmactivityevent',
            name='rm_user_id',
        ),
        migrations.RemoveField(
            model_name='rmactivityevent',
            name='started_at',
        ),
        migrations.RemoveField(
            model_name='rmactivityevent',
            name='state',
        ),
        migrations.RemoveField(
            model_name='rmactivityevent',
            name='team',
        ),
        migrations.AddIndex(
            model_name='rmactivityevent',
            index=models.Index(fields=['tenant', 'event_type'], name='rm_events_tenant_type_idx'),
        ),
        migrations.AddIndex(
            model_name='rmactivityevent',
            index=django.contrib.postgres.indexes.GinIndex(fields=['event_data'], name='rm_events_data_gin_idx'),
        ),
    ]
