# Generated by Django 5.2.4 on 2025-09-08 23:25

import django.db.models.constraints
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authz', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tenantmembership',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='tenantmembership',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='tenantmembership',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tenantmembership',
            name='user_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='tenantmembership',
            index=models.Index(fields=['tenant'], name='authz_tm_tenant_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantmembership',
            index=models.Index(fields=['role'], name='authz_tm_role_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantmembership',
            index=models.Index(django.db.models.functions.text.Lower('email'), name='authz_tm_email_lower_idx'),
        ),
        migrations.AddConstraint(
            model_name='tenantmembership',
            constraint=models.CheckConstraint(condition=models.Q(('email__isnull', True), ('email', django.db.models.functions.text.Lower('email')), _connector='OR'), name='authz_tm_email_lower_chk'),
        ),
        migrations.AddConstraint(
            model_name='tenantmembership',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('tenant', 'role', 'email'), name='uniq_authz_tm_tenant_role_email'),
        ),
        migrations.AlterModelTable(
            name='tenantmembership',
            table='authz_tenantmembership',
        ),
    ]
