# Generated by Django 5.2.4 on 2025-09-08 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authz', '0002_alter_tenantmembership_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantmembership',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
