# Generated by Django 5.2.4 on 2025-09-08 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authz', '0003_alter_tenantmembership_email'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tenantmembership',
            name='uniq_authz_tm_tenant_role_email',
        ),
        migrations.AddConstraint(
            model_name='tenantmembership',
            constraint=models.UniqueConstraint(fields=('tenant', 'role', 'email'), name='uniq_authz_tm_tenant_role_email'),
        ),
        migrations.AddConstraint(
            model_name='tenantmembership',
            constraint=models.UniqueConstraint(condition=models.Q(('user_id__isnull', False)), fields=('tenant', 'user_id'), name='uniq_authz_tm_tenant_user_nn'),
        ),
    ]
