# Generated by Django 5.2.4 on 2025-09-12 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authz', '0004_remove_tenantmembership_uniq_authz_tm_tenant_role_email_and_more'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantmembership',
            name='user_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='tenantmembership',
            index=models.Index(fields=['user_id'], name='authz_tm_user_id_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantmembership',
            index=models.Index(fields=['is_active'], name='authz_tm_is_active_idx'),
        ),
    ]
