# Generated by Django 5.2.4 on 2025-09-22 01:50

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authz', '0005_alter_tenantmembership_user_id_and_more'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='role',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(django.db.models.functions.text.Lower('key'), name='authz_role_lower_key_idx'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('key'), models.F('tenant'), name='uniq_authz_role_tenant_lower_key'),
        ),
    ]
