# Generated by Django 5.2.4 on 2026-01-07 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authz', '0006_alter_role_unique_together_and_more'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantmembership',
            name='user_parent_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='tenantmembership',
            index=models.Index(fields=['user_parent_id'], name='authz_tm_user_parent_id_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantmembership',
            index=models.Index(fields=['tenant', 'user_parent_id'], name='authz_tm_tenant_user_parent'),
        ),
    ]
