# Generated by Django 5.2.4 on 2026-01-08 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authz', '0007_tenantmembership_user_parent_id_and_more'),
    ]

    operations = [
        # Step 1: Remove the old UUID field
        migrations.RemoveField(
            model_name='tenantmembership',
            name='user_parent_id',
        ),
        # Step 2: Add the new ForeignKey field
        migrations.AddField(
            model_name='tenantmembership',
            name='user_parent_id',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='direct_reports',
                to='authz.tenantmembership',
                db_index=True
            ),
        ),
    ]
