# Generated by Django 5.2.4 on 2026-02-12 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authz', '0008_change_user_parent_id_to_foreignkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantmembership',
            name='company_name',
            field=models.CharField(blank=True, help_text='Optional company name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenantmembership',
            name='name',
            field=models.CharField(blank=True, help_text="User's display name", max_length=255, null=True),
        ),
    ]
