# Generated by Django 5.2.4 on 2026-02-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authz', '0010_migrate_legacy_user_data_to_tenant_membership'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tenantmembership',
            index=models.Index(fields=['name'], name='authz_tm_name_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantmembership',
            index=models.Index(fields=['company_name'], name='authz_tm_company_name_idx'),
        ),
    ]
