# Generated by Django 5.2.4 on 2026-03-11 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authz', '0011_add_indexes_for_name_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermission',
            name='membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authz.tenantmembership'),
        ),
        migrations.AlterUniqueTogether(
            name='userpermission',
            unique_together={('membership', 'permission')},
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='effect',
            field=models.CharField(choices=[('allow', 'allow'), ('deny', 'deny')], default='allow', max_length=8),
        ),
        migrations.RemoveField(
            model_name='userpermission',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='userpermission',
            name='user_id',
        ),
    ]
