# Generated by Django 5.2.4 on 2026-04-29 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authz', '0016_authz_remaining_soft_delete'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='groupmembership',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='grouppermission',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='grouprole',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='permission',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='role',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='rolepermission',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='tenantmembership',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='usergroup',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='userpermission',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='groupmembership',
            name='is_deleted',
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='grouppermission',
            name='is_deleted',
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='grouprole',
            name='is_deleted',
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='permission',
            name='is_deleted',
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='role',
            name='is_deleted',
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='is_deleted',
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='tenantmembership',
            name='is_deleted',
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='is_deleted',
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='is_deleted',
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
    ]
