# Generated by Django 5.2.4 on 2025-10-13 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('crm_records', '0003_ruleset'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('event_name', models.CharField(db_index=True, max_length=100)),
                ('matched', models.BooleanField(default=False)),
                ('actions', models.JSONField(blank=True, default=list)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('duration_ms', models.FloatField(blank=True, null=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_executions', to='crm_records.record')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm_records.ruleset')),
                ('tenant', models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='core.tenant')),
            ],
            options={
                'db_table': 'rule_exec_logs',
                'indexes': [models.Index(fields=['tenant', 'event_name', '-created_at'], name='rule_exec_l_tenant__1c4021_idx')],
            },
        ),
    ]
