# Generated by Django 5.2.4 on 2025-12-03 10:28

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('crm_records', '0004_ruleexecutionlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityTypeSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('entity_type', models.CharField(db_index=True, help_text="The entity type (e.g., 'lead', 'ticket', 'job')", max_length=100)),
                ('attributes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, help_text="List of all attribute paths for this entity type (e.g., ['id', 'name', 'data.email', 'data.phone'])", size=None)),
                ('description', models.TextField(blank=True, help_text='Optional description of this entity type schema', null=True)),
                ('tenant', models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='core.tenant')),
            ],
            options={
                'db_table': 'entity_type_schemas',
                'indexes': [models.Index(fields=['tenant', 'entity_type'], name='entity_type_tenant__1ed2d5_idx')],
                'unique_together': {('tenant', 'entity_type')},
            },
        ),
    ]
