# Generated by Django 5.2.4 on 2025-12-08 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_records', '0005_entitytypeschema'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitytypeschema',
            name='rules',
            field=models.JSONField(blank=True, default=list, help_text="List of scoring rules for this entity type. Each rule has 'attr', 'operator', 'value', and 'weight'."),
        ),
    ]
