# Generated by Django 5.2.4 on 2026-01-16 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('crm_records', '0014_allow_null_pyro_data'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='apisecretkey',
            new_name='api_secret__secret__cdef2f_idx',
            old_name='api_secret_hash_act_idx',
        ),
        migrations.RenameIndex(
            model_name='apisecretkey',
            new_name='api_secret__tenant__0ebea5_idx',
            old_name='api_secret_ten_act_idx',
        ),
        migrations.AlterField(
            model_name='apisecretkey',
            name='secret_key_hash',
            field=models.CharField(db_index=True, default='', help_text='bcrypt hash of the raw secret (pgcrypto crypt). Do NOT store plaintext secrets.', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='crm_records.record'),
        ),
        # These indexes were already created in migrations 0012 and 0013 using raw SQL
        # Using RunSQL with IF NOT EXISTS to make this idempotent
        migrations.RunSQL(
            sql="""
            CREATE INDEX IF NOT EXISTS records_data_gin_idx ON records USING gin (data);
            CREATE INDEX IF NOT EXISTS records_pyro_data_gin_idx ON records USING gin (pyro_data);
            """,
            reverse_sql="""
            DROP INDEX IF EXISTS records_data_gin_idx;
            DROP INDEX IF EXISTS records_pyro_data_gin_idx;
            """,
        ),
    ]
