# Generated by Django 5.2.4 on 2026-02-10 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('crm_records', '0016_add_call_attempt_matrix'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='callattemptmatrix',
            new_name='call_attemp_tenant__80df9c_idx',
            old_name='crm_records_callattemptmatrix_tenant_lead_type_idx',
        ),
        migrations.AlterField(
            model_name='callattemptmatrix',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='core.tenant'),
        ),
        # Indexes already exist from 0012/0013/0015; use IF NOT EXISTS so migration is idempotent
        migrations.RunSQL(
            sql="""
            CREATE INDEX IF NOT EXISTS records_data_gin_idx ON records USING gin (data);
            CREATE INDEX IF NOT EXISTS records_pyro_data_gin_idx ON records USING gin (pyro_data);
            """,
            reverse_sql="""
            DROP INDEX IF EXISTS records_data_gin_idx;
            DROP INDEX IF EXISTS records_pyro_data_gin_idx;
            """,
        ),
    ]
