# Generated by Django 5.2.4 on 2026-02-16 22:24

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('crm_records', '0018_merge_20260214_1630'),
    ]

    operations = [
        # Use RunSQL with IF NOT EXISTS: records_data_gin_idx already exists from 0012
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddIndex(
                    model_name='record',
                    index=django.contrib.postgres.indexes.GinIndex(fields=['data'], name='records_data_gin_idx'),
                ),
                migrations.AddIndex(
                    model_name='record',
                    index=django.contrib.postgres.indexes.GinIndex(fields=['pyro_data'], name='records_pyro_data_gin_idx'),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    CREATE INDEX IF NOT EXISTS records_data_gin_idx ON records USING gin (data);
                    CREATE INDEX IF NOT EXISTS records_pyro_data_gin_idx ON records USING gin (pyro_data);
                    """,
                    reverse_sql="""
                    DROP INDEX IF EXISTS records_pyro_data_gin_idx;
                    """,
                ),
            ],
        ),
    ]
