# Generated by Django 5.2.4 on 2026-03-02 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_enable_pg_trgm'),
        ('crm_records', '0020_partner_event'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='partnerevent',
            new_name='partner_eve_tenant__0d3ff2_idx',
            old_name='partner_ev_tenant_partner_created_idx',
        ),
        migrations.RenameIndex(
            model_name='partnerevent',
            new_name='partner_eve_tenant__92c06b_idx',
            old_name='partner_ev_tenant_status_created_idx',
        ),
        migrations.AlterField(
            model_name='partnerevent',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='core.tenant'),
        ),
    ]
