# Generated by Django 5.2.4 on 2026-03-11 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_records', '0024_unique_lead_praja_id_per_tenant'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='apisecretkey',
            new_name='api_secret__secret_b8e582_idx',
            old_name='api_secret_sec_act_idx',
        ),
    ]
