# Generated by Django 5.2.4 on 2026-03-20 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authz', '0013_tenantmembership_department'),
        ('core', '0003_enable_pg_trgm'),
        ('crm_records', '0025_rename_api_secret_sec_act_idx_api_secret__secret_b8e582_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True)),
                ('filter_conditions', models.JSONField(default=dict)),
                ('is_system', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='UserBucketAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('priority', models.IntegerField(default=100)),
                ('pull_strategy', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_records.bucket')),
                ('tenant', models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='core.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authz.tenantmembership')),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
        migrations.AddIndex(
            model_name='bucket',
            index=models.Index(fields=['tenant', 'slug'], name='crm_records_tenant__f51769_idx'),
        ),
        migrations.AddIndex(
            model_name='bucket',
            index=models.Index(fields=['tenant', 'is_active'], name='crm_records_tenant__4cd0d8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bucket',
            unique_together={('tenant', 'slug')},
        ),
        migrations.AddIndex(
            model_name='userbucketassignment',
            index=models.Index(fields=['tenant', 'user'], name='crm_records_tenant__bc7ec8_idx'),
        ),
        migrations.AddIndex(
            model_name='userbucketassignment',
            index=models.Index(fields=['tenant', 'bucket', 'priority'], name='crm_records_tenant__6afd0f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userbucketassignment',
            unique_together={('tenant', 'user', 'bucket')},
        ),
    ]
