# Generated by Django 5.2.4 on 2026-04-29 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_records', '0029_crm_records_soft_delete'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='apisecretkey',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='bucket',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='callattemptmatrix',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='entitytypeschema',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='eventlog',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='partnerevent',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='record',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='ruleexecutionlog',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='ruleset',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='scoringrule',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='userbucketassignment',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='apisecretkey',
            name='is_deleted',
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='bucket',
            name='is_deleted',
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='callattemptmatrix',
            name='is_deleted',
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='entitytypeschema',
            name='is_deleted',
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='is_deleted',
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='partnerevent',
            name='is_deleted',
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='record',
            name='is_deleted',
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='ruleexecutionlog',
            name='is_deleted',
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='ruleset',
            name='is_deleted',
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='scoringrule',
            name='is_deleted',
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='userbucketassignment',
            name='is_deleted',
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
    ]
