# Generated by Django 5.2.4 on 2025-08-19 01:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('intervals', models.JSONField(default=list)),
                ('max_attempts', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1)])),
                ('business_hours_only', models.BooleanField(default=False)),
                ('timezone', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=64)),
                ('action', models.CharField(choices=[('call', 'Call')], max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('due_at', models.DateTimeField(db_index=True)),
                ('priority', models.SmallIntegerField(default=0)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=5)),
                ('locked_by', models.CharField(blank=True, max_length=64, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='scheduler.taskpolicy')),
            ],
        ),
        migrations.CreateModel(
            name='AttemptLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_no', models.PositiveSmallIntegerField()),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('outcome', models.CharField(choices=[('NO_ANSWER', 'No Answer'), ('BUSY', 'Busy'), ('CALL_DROPPED', 'Call Dropped'), ('CONNECTED_POSITIVE', 'Connected Positive'), ('CONNECTED_NEGATIVE', 'Connected Negative'), ('CALLBACK_REQUESTED', 'Callback Requested'), ('INVALID_NUMBER', 'Invalid Number')], max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_logs', to='scheduler.scheduledtask')),
            ],
        ),
        migrations.AddIndex(
            model_name='scheduledtask',
            index=models.Index(fields=['status', 'due_at'], name='scheduler_s_status_d2367a_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledtask',
            index=models.Index(fields=['content_type', 'object_id', 'status'], name='scheduler_s_content_a8b1e5_idx'),
        ),
    ]
