# Generated by Django 5.2.4 on 2025-08-19 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('scheduler', '0002_taskpolicy_audit_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskpolicy',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='taskpolicy',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='core.tenant'),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='taskpolicy',
            index=models.Index(fields=['tenant', '-created_at'], name='scheduler_t_tenant__b7ba02_idx'),
        ),
    ]
