# Generated by Django 5.2.4 on 2026-04-29 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0004_idle_in_transaction_session_timeout'),
        ('scheduler', '0003_alter_taskpolicy_options_scheduledtask_tenant_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduledtask',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='attemptlog',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='attemptlog',
            name='is_deleted',
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='is_deleted',
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='taskpolicy',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='taskpolicy',
            name='is_deleted',
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='taskpolicy',
            name='key',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='scheduledtask',
            index=models.Index(fields=['tenant', '-created_at'], name='scheduler_s_tenant__8ef8ae_idx'),
        ),
        migrations.AddConstraint(
            model_name='taskpolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('deleted_at__isnull', True)), fields=('key',), name='scheduler_taskpolicy_key_uniq_alive'),
        ),
    ]
